version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: api
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/vendorDB
      - RABBITMQ_URL=amqp://rabbitmq
      - PORT=3000
    depends_on:
      - mongo
      - rabbitmq

  worker:
    build:
      context: .
      dockerfile: worker/Dockerfile
    container_name: worker
    environment:
      - MONGO_URL=mongodb://mongo:27017/vendorDB
      - RABBITMQ_URL=amqp://rabbitmq
    depends_on:
      - mongo
      - rabbitmq

  vendor-mocks:
    build:
      context: .
      dockerfile: vendor-mocks/Dockerfile
    container_name: vendor-mocks
    ports:
      - "4000:4000"

  k6:
    image: grafana/k6
    command: run /scripts/load-test.js
    volumes:
      - ./load-test.js:/scripts/load-test.js
    depends_on:
      - api
    networks:
      - default

volumes:
  mongo-data:
